# -*- coding: utf-8 -*-
"""handwritting_recognition_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VorJi77ythOj_Z23HArJmZxCFJ3a-tE8
"""

## IMPORTS & SETUP

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

## LOADIND DATASET

train_df = pd.read_csv("mnist_train.csv")
test_df = pd.read_csv("mnist_test.csv")

## DATA PREPARATION (PYTHONIC & CLEAN)

def prepare_data(df):
    df.dropna(inplace=True)
    X = df.iloc[:, 1:].values
    y = df.iloc[:, 0].values
    return X, y

X_train, y_train = prepare_data(train_df)
X_test, y_test = prepare_data(test_df)

# Normalize pixel values
X_train = X_train / 255.0
X_test = X_test / 255.0

## KNN MODEL

def train_knn(X_train, y_train, k=3):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    return model

knn_model = train_knn(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

## NEURAL NETWORK MODEL

def train_mlp(X_train, y_train):
    model = MLPClassifier(hidden_layer_sizes=(128,), max_iter=10, random_state=42)
    model.fit(X_train, y_train)
    return model

mlp_model = train_mlp(X_train, y_train)

y_pred_mlp = mlp_model.predict(X_test)

## EVALUATION

def evaluate(y_true, y_pred, model_name):
    acc = accuracy_score(y_true, y_pred)
    print(f"{model_name} Accuracy: {acc:.4f}")
    return acc

acc_knn = evaluate(y_test, y_pred_knn, "KNN")
acc_mlp = evaluate(y_test, y_pred_mlp, "MLP")

## CONFUSION MATRIX VISUALIZATION

def plot_confusion_matrix(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure()
    plt.imshow(cm)
    plt.title(title)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.colorbar()
    plt.show()

plot_confusion_matrix(y_test, y_pred_knn, "KNN Confusion Matrix")
plot_confusion_matrix(y_test, y_pred_mlp, "MLP Confusion Matrix")

## MISCLASSIFIED SAMPLES

def show_misclassified(X, y_true, y_pred, num_samples=5):
    mis_idx = np.where(y_true != y_pred)[0]

    for i in range(min(num_samples, len(mis_idx))):
        idx = mis_idx[i]
        plt.imshow(X[idx].reshape(28, 28), cmap='gray')
        plt.title(f"True: {y_true[idx]} | Pred: {y_pred[idx]}")
        plt.axis('off')
        plt.show()

print("KNN Misclassified Samples:")
show_misclassified(X_test, y_test, y_pred_knn)

print("MLP Misclassified Samples:")
show_misclassified(X_test, y_test, y_pred_mlp)

## MODEL COMPARISON

results = pd.DataFrame({
    "Model": ["KNN", "MLP"],
    "Accuracy": [acc_knn, acc_mlp]
})

print(results)

## TRYING DIFFERENT KEY VALUES

for k in [1, 3, 5]:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    print(f"K={k} Accuracy={acc:.4f}")